# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e33ffc44046d3830cf7d7f5e0f2850468fd2c83b47286bca8a0fd234fc14091de63ada1c07aeea92d5e98e6e93b518f4f6dfe6fe65bdc5d2527f9e92d4871fa

test:
  secret_key_base: 8dcabefd2f9bd07dcb6bad57816d723c4a649d6f2b60197f53c4aae0fedb13c752821e017905004229be08a9f08866d1ee3d3e62dcfde0c5d32874905afdc73e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
